server:
  port: 8185
spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    password: root
#    url: jdbc:mariadb://localhost:3306/credentialdb
#    username: root
  application:
       name: api-gateway
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  cloud:
     gateway:
       enabled: true
       routes:
       - id: customer-microservice
         uri: http://localhost:8181/
         predicates:
         - Path=/customer/**
         
       - id: employee-microservice
         uri: http://localhost:8182/
         predicates:
         - Path=/employee/**
         
       - id: login-service
         uri: http://localhost:8183/
         predicates:
         - Path=/register/**

eureka:
  client:
      register-with-eureka: true
      service-url:
         defaulZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/} 

logging:
    file:
      name: api-gateway.log
management:
  endpoints:
    web:
      exposure:
        include: "*"            